### ISSUE TITLE
Does not run initial-setup tasks

### ISSUE THREAD

**Issue by n8willis** [diddlesnaps/tvheadend#1]
Just tried this snap out. It does succeed in installing, but it does not launch the tvheadend setup/initial-configuration program afterward, so you don't get a working installation.

**Comment by diddledan** [comment]
I'm not sure what you mean by "setup/initial configuration program". The daemon should be started automatically on installation. All you need to do is open your browser and point it at http://localhost:9981/. The initial configuration AFAIK is all performed in a browser, and so there is no configuration program.

**Comment by n8willis** [comment]
I mean the step where you set up an admin username/pwd which you need to access the web configuration interface.

And, FYI, I am not running this on localhost, but on a headless machine, which means that the web UI needs to be accessible from other addresses (and it currently isn't...).

**Comment by diddledan** [comment]
I'm going to close this issue as I think it is working as expected. If this is still a problem either re-open this issue or file a new issue.
