### ISSUE TITLE
Folder permissions

### ISSUE THREAD

**Issue by sja** [diddlesnaps/tvheadend#5]
Thanks for the snap, it was the easiest installation I ever had of tvheadend.

But it would be much more useful if I could define the recordings path outside of the snap chroot. At least the home plug (or whatever this is called in snappy) would be good.

In my case, I prefer a mounted network share to save my recordings. Is this possible?

**Comment by diddledan** [comment]
The snap has the `removable-media` plug specified, which you can enable with the Software Centre in Ubuntu or the Snap Store snap on other systems, or you can enable it in the terminal with `snap connect tvheadend:removable-media`.

The removable-media interface allows a snap to access the following paths:
- `/media/*/` Mount points could be in /media/<user>/*
- `/run/media/*/` # Mount points could be in /run/media/<user>/*
- `/mnt/*`

**Comment by diddledan** [comment]
I'm going to close this issue for now. If it's still a problem either reopen this issue or file a new one.
