### ISSUE TITLE
TV adapter not found

### ISSUE THREAD

**Issue by capruro** [diddlesnaps/tvheadend#6]
Hi, I tried to install the snap on my raspberry pi 4 with the official tv hat on ubuntu 20.04 (arm64), but tvheadend is unable to find the tuner, I didn't have the same issue on standard package. Is this a snap limitation or should I enable some settings on snap/tvheadend?

Thank you!

Edit: I made sure that the DVB plug was enabled, but still it can't detect any tuner.

**Comment by capruro** [comment]
Hello, I figured out that I had to do the following:

`snap connect tvheadend:dvb`

and after reboot it worked properly.
It would be nice to have some more documentation about it, thank you anyway for your snap!

**Comment by antoniosap** [comment]
pi@raspberrypi:~ $ sudo snap connect tvheadend:dvb
error: cannot resolve connection, slot snap name is empty
